export default {
  items:[
    {        
      "name":"数据概览",
      "url":"/",
      "children":[]
    },
    {        
      "name":"实时数据",
      "url":"/MachineRoom",
      "children":[]
    },
    {        
      "name":"历史数据",
      "url":"/",
      "children":[
        {
          "name":"空压机一号",
          "url":"/Machine",
        },
        {
          "name":"空压机二号",
          "url":"/Marchine",
        },
      ]
    },
  ]
}