export default [
    {        
      "name":"数据概览",
      "url":"/Home",
      "children":[]
    },
    {        
      "name":"实时数据",
      "url":"/Home/MachineRoom",
      "children":[]
    },
    {        
      "name":"历史数据",
      "url":"/",
      "children":[
        {
          "name":"空压机一号",
          "url":"/Home/Machine",
        },
        {
          "name":"空压机二号",
          "url":"/Home/Marchine",
        },
      ]
    },
  ]